daac/main.tf
daac/terraform.tfvars
daac/variables.tf

This change attempts to resolve issue #14  and #15.  To do that, it separates out standard, protected and public bucket lists.  It also hard codes in the internal bucket.  It enables the necessary logging for EMS reporting per these Cumulus instructions.
https://nasa.github.io/cumulus/docs/deployment/server_access_logging
One problem introduced by this code occurs during the first `make daac`, Terraform wants to delete/recreate the internal/protected/public buckets.  The  `lifecycle {prevent_destroy = true}` on the buckets prevents that.  
If a daac wants to retain the contents of those buckets I think they could sync their contents to other buckets, then empty and destroy them manually.  `make daac` will then recreate them and they can sync back.  
If the contents can be destroyed, the …

make bucket mapping more flexible include necessary logging for EMS

---

daac/s3-replicator.tf
daac/variables.tf
daac/variables/dev.tfvars

Per these Cumulus instructions
https://nasa.github.io/cumulus/docs/additional-deployment-options/share-s3-access-logs
the s3-replicator module is used to replicate access data to the metrics account.
It is only needed in accounts which are integrated with metrics, however, since
terraform doesn't have the notion of optional modules, this module defaults to
replicating from the normal internal bucket prefix to another prefix in the same
bucket
For environments which really do send info to metrics you can override the target
bucket and prefix in that environment's tfvars file.
Another option would be to name the module as something like s3-replicator.tf.optional and put some logic in the make process to copy it to s3-replicator.tf only for environments which do need to implement.
I felt …

add s3_replicator module

---

daac/s3-replicator.tf

remove extra / at end of source-prefix.  causes lambda function to fail.

fix source_prefix path

---

Dockerfile
daac/main.tf
daac/outputs.tf
daac/s3-replicator.tf
workflows/main.tf

This should remove the following warning:
```Bash
Warning: Interpolation-only expressions are deprecated
on common.tf line 35, in locals:
35:     region = "${data.aws_region.current.name}"
```

CIRRUS-DAAC: Replaced interpolation expressions with HCL2 expressions

---

daac/main.tf
daac/terraform.tfvars
daac/variables.tf
daac/variables/dev.tfvars

This allows for whitelisting buckets that we need to access, but we don't create (ie are in another account, or shared across maturities)

Add new "partner" bucket type for external/non-created buckets

---

CHANGELOG.md
rds/variables.tf

Deploy fails because AWS automatically upgrades to the latest version and doesn't let terraform perform a downgrade:
```
Error: Failed to modify RDS Cluster (sds-n-cumulus-dev-rds-cluster): InvalidParameterCombination: Cannot find upgrade target from 10.serverless_18 with requested version 10.14 for serverless engine mode.
status code: 400, request id: c21bf34b-704d-491a-9474-2f730e5079ef
```

Bump engine version to latest version of 10.x

---

daac/main.tf
jenkins/Jenkinsfile

Each running container needs to have a unique name, so using the same hardcoded name `cirrus-core` for every pipeline would prevent us from running multiple concurrent builds. I decided to go with the job name, and not include the build id, so that if the container gets stuck, we will be notified by subsequent builds erroring out instead of the stuck container just being forgotten about.

Use job name as container name in Jenkins

---

jenkins/Jenkinsfile

Right now these commands will fail when encountering a commit id, however, we want to be able to pin to a commit id to prevent upstream changes from breaking our builds. This should allow all types of refs to work correctly.

Only run git pull if CORE_REF references an actual branch

---

CHANGELOG.md
daac/main.tf
daac/s3-replicator.tf
rds/main.tf
workflows/dev-requirements.txt
workflows/main.tf
workflows/variables.tf

* Upgrade to [Cumulus v14.1.0](https://github.com/nasa/Cumulus/releases/tag/v14.1.0)
* Bump RDS engine version to 11.13
* Exposes the new `cloudwatch_log_retention_periods` as mentioned in the release notes in case a DAAC wants to modify the retention of any CloudWatch log groups.
* updated the terraform `aws` provider in the `daac` and `workflows` modules to match those in the underlying Cumulus modules.
* **Reminder** - this version requires [Cumulus Dashboard v12.0.0](https://github.com/nasa/cumulus-dashboard/releases/tag/v12.0.0)
* Also, any ECS tasks are required to use the `cumuluss/cumulus-ecs-task:1.8.0` docker image.  This requirement is listed in the [Cumulus v11.1.8](https://github.com/nasa/Cumulus/releases/tag/v14.1.0) breaking changes section.

upgrade Cumulus to v14.1.0

---

daac/main.tf

The key name was conflicting with and being overridden by the file uploaded by the cumulus module.

Change bucket map key uploaded by daac module

---

daac/dashboard.tf
daac/main.tf
daac/outputs.tf

This fixes warnings about 
- Encryption configuration block being deprecated
- `aws_s3_bucket_object` being deprecated
There is another warning about the `acl` configuration being deprecated, but that needs to be replaced by a bucket policy anyway as it causes failures when deploying from scratch.

Fix deprecation warnings

---

CHANGELOG.md
cumulus/provider.tf
daac/main.tf
daac/provider.tf
daac/s3-replicator.tf
dashboard/provider.tf
data-migration1/variables/example.tfvars
rds/data.tf
rds/main.tf
rds/provider.tf
workflows/main.tf
workflows/provider.tf

Update to [Cumulus v17.0.0](https://github.com/nasa/cumulus/releases/tag/v17.0.0)
Update to Terraform provider to >= 5.0.0

Update Cumulus to v17.0.0

---

CHANGELOG.md
daac/distribution_bucket_policy.tf
daac/variables.tf

When setting up TEA behind a CloudFront distribution, any buckets that you will be distributing data from need to have a bucket policy that allows the CloudFront OAI to read the data. These bucket policies may be expanded in the future or maybe left to be expanded in the downstream forks.

Add distribution bucket policy resources

---

daac/outputs.tf
daac/variables.tf
dashboard/outputs.tf
dashboard/variables.tf
rds/outputs.tf
rds/variables.tf
workflows/outputs.tf
workflows/variables.tf

This PR adds the CIRRUS-core and CIRRUS-DAAC versions to the `daac`, `dashboard`, `rds`, and `workflows` modules. It also puts the variables and outputs in alphabetical order. If the file contained screaming snake case and snake case, I put the screaming snake case in alphabetical order in its own section.

Add CIRRUS versions to terraform outputs

---

CHANGELOG.md
Makefile
daac/locals.tf
daac/s3-replicator.tf
daac/terraform.tfvars
daac/variables.tf
workflows/main.tf

I found that in our prod account we still have some of these `protected-1`, `public-1`, etc and `acme-*` buckets deployed even though we have no use for them. So I decided to rework the defaults here a little bit so that the examples are not deployed by default and you need to explicitly opt-in to having any public/private/protected buckets get deployed.
- Fix some formatting things
- Clean up the daac variables a bit
- Add descriptions
- Remove usage of `any` type
- Default to empty bucket lists
- Update some version defaults
- Fix an issue with the Makefile when using a non-default dashboard repo name

Clean up various examples and defaults

---

CHANGELOG.md
daac/distribution_bucket_policy.tf
daac/locals.tf
daac/terraform.tfvars
daac/variables.tf
daac/variables/sbx.tfvars

At ASF we've needed to add several additional bucket features such as infrequent access and different logging configurations to our buckets. Using the existing setup this requires adding a new bucket list for each feature and duplicating the bucket names that the feature should be applied to.
To simplify this I decided to rework how the buckets are configured in the daac variables. Instead of separate lists for each bucket type there is now a single map of bucket name to config options where you can enable additional features on a bucket by bucket basis.
For example (note the only additional feature implemented in this repo is the `oai` for buckets that distribute data via CloudFront):
```hcl
bucket_config_base = {
"private"   = { type = "standard" }
"protected" = { type = "protected" } …
```

Refactor bucket config to use a single map

---

CHANGELOG.md
Dockerfile
Makefile
README.md
tests.Dockerfile
workflows/dev-requirements.txt

Currently, [CIRRUS-core ](https://github.com/asfadmin/CIRRUS-core/blob/master/Dockerfile)and CIRRUS-DAAC have similar Dockerfiles. This updates CIRRUS-DAAC's Dockerfile to focus just on tests. This will make it more clear when to use the CIRRUS-DAAC or CIRRUS-core Dockerfile. It also aligns with the CIRRUS-DAAC README.

Update Dockerfile to be for tests 

---

CHANGELOG.md
workflows/locals.tf
workflows/main.tf

Reverts asfadmin/CIRRUS-DAAC#106
Reverting till I fix the issue with the Python update in CIRRUS-core. While CIRRUS-DAAC's code ran, there were issues with more complex workflows.

Revert "PR-5950: Update Python to 3.10"

---

CHANGELOG.md
cumulus/provider.tf
daac/dashboard.tf
daac/main.tf
daac/provider.tf
daac/s3-replicator.tf
dashboard/locals.tf
dashboard/provider.tf
rds/locals.tf
rds/main.tf
rds/provider.tf
workflows/locals.tf
workflows/main.tf
workflows/provider.tf

This will apply the deployment tag to all resources automatically without us needing to remember to add it every time. This functionality was added in `v3.38.0` so might not have been available when Cumulus/CIRRUS was originally started.
https://developer.hashicorp.com/terraform/tutorials/aws/aws-default-tags

Use aws provider level `default_tags` configuration

---

CHANGELOG.md
workflows/locals.tf
workflows/main.tf

After some investigation, the issue in this [PR](https://github.com/asfadmin/CIRRUS-DAAC/pull/106) was caused by an ASF repo that our ingest was using.

Update Lambda python version to 3.9

---

CHANGELOG.md
daac/distribution_bucket_policy.tf
daac/locals.tf
daac/terraform.tfvars
daac/variables.tf
daac/variables/sbx.tfvars

The config overrides didn't work correctly because missing values are treated the same way as explicit nulls. I was assuming it would work similar to python dictionaries and the `**` merge operator, but that's not the case. The missing values would basically overwrite the default values instead of being ignored.

PR-6093 Refactor bucket config to use a single map (again)

---

CHANGELOG.md
rds/main.tf

The cumulus RDS module defines a legacy provider configuration which prevents our provider configuration from taking effect.
See https://bugs.earthdata.nasa.gov/browse/CUMULUS-3896

Pass tags to cumulus RDS module manually

---

.github/workflows/deploy.yml
CHANGELOG.md

Updating the secret like this works:
```terraform
data "aws_secretsmanager_secret_version" "rds_login" {
secret_id  = module.rds_cluster.admin_db_login_secret_arn
version_id = module.rds_cluster.admin_db_login_secret_version
}
resource "aws_secretsmanager_secret_version" "rds_login_override" {
secret_id = module.rds_cluster.admin_db_login_secret_arn
secret_string = jsonencode(
merge(
jsondecode(data.aws_secretsmanager_secret_version.rds_login.secret_string),
{
disableSSL         = var.disableSSL
rejectUnauthorized = var.rejectUnauthorized
},
)
)
}
```
However, the rds module is a 'legacy' module due to it including a `provider` block, so terraform doesn't allow us to use a `depends_on` with it, which would be required since we have to update the secret BEFORE deploying the module.
I added …

Add SNAPSHOT_IDENTIFIER variable to GitHub Actions CI

---

CHANGELOG.md
rds/main.tf
rds/variables.tf

These variables are needed for adjusting the available ACUs on the database as well as tweaking other capacity related settings.

Add variables to `rds` module for tweaking resource allocation settings

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
CHANGELOG.md

Cumulus v20 requires dashboard v13.
There is a bug in version 13.0.0 where the Dockerfile command used to build the dashboard running `/bin/build_dashboard_via_docker.sh` does not install the dependencies successfully. This was fixed in https://github.com/nasa/cumulus-dashboard/pull/1174 but has not yet been released.

PR-6337 Update default dashboard ref to minimum required version

---

rds/variables/sbx.tfvars

Sandbox accounts may have a lot of stacks that are largely idle. This should allow the database to scale down when not in use. 
Note that as of engine version `13.15` the minimum becomes `0`, however the default engine version pinned by cumulus is `13.12`. I'm not sure if there are any risks associated with upgrading that, so I'm leaving it at the default for now.
Deployment to `daac-cumulus-sbx` succeeded.

Lower RDS min_capacity to smallest allowed value in sandbox

---

.github/workflows/deploy.yml
CHANGELOG.md
cumulus/variables/sbx.tfvars
workflows/locals.tf
workflows/requirements.txt

Python 3.9 will hit EOL in October.

PR-6919 Update python to 3.11
