asfadmin/CIRRUS-DAAC

daac/terraform.tfvars
workflows/main.tf

Thought we should update these too.

change default CMA version, update workflow.zip version

---

CHANGELOG.md
workflows/main.tf

small change for Cumulus 1.19.0

update for Cumulus v1.19.0

---

scripts/deploy-pcrs.sh

ignore known hosts file to prevent man-in-the-middle warning
use approved `--user "${RAWAUTH}"` instead of form data post

Untangle some loose bits in the pcrs script

---

jenkins/Jenkinsfile

buckets can't have UPPERcase letters

Update maturity to lowercase

---

Makefile
README.md

I made some updates to the dashboard make target.  I successfully deployed with SERVED_BY_CUMULUS_API = true.
What do you think?

Dashboard fix

---

scripts/purge.py

Script to purge all deployment resources based on tag

---

cumulus/variables/dev.tfvars
cumulus/variables/int.tfvars
cumulus/variables/prod.tfvars
cumulus/variables/test.tfvars

Related - https://github.com/asfadmin/CIRRUS-core/pull/81

add comment about using latest AMI from CIRRUS-core

---

CHANGELOG.md
daac/s3-replicator.tf
workflows/main.tf

I thought it would be good to have a version which used the latest 2.0 release before we start work on 3.0

upgrade Cumulus to v2.0.7

---

CHANGELOG.md
Makefile
daac/outputs.tf
daac/s3-replicator.tf
workflows/main.tf

should contain the changes needed for Cumulus v3.0.0

V3.0.0.0 rc

---

CHANGELOG.md
daac/main.tf
daac/s3-replicator.tf
workflows/main.tf

In addition to v3.0.1 upgrade, this PR also adds encryption of buckets and tags for all buckets.

V3.0.1.0 rc

---

CHANGELOG.md
daac/main.tf
workflows/main.tf

update terraform aws provider to 3.19.x plus some auto formatting of .tf files

terraform aws provider update

---

scripts/dicpelr.py
scripts/purge.py
scripts/src/dicpelr.py

Currently, the only changes to purge.py are the changes my IDE changed for the formatting. I will be adding code in purge.py that creates a dicpelr (dispel(r)) object that will destroy all (That I can find at the moment) resources in the correct order. There is still code I need to add. I want to keep my pull requests relatively small.

Added functionality for purging Cumulus 

---

CHANGELOG.md
daac/s3-replicator.tf
workflows/main.tf

See also https://github.com/asfadmin/CIRRUS-core/pull/105

Upgrade to Cumulus to v5.0.1

---

CHANGELOG.md
Dockerfile
daac/main.tf
daac/versions.tf
workflows/main.tf
workflows/versions.tf

updates for Terraform v0.13.6

---

CHANGELOG.md
daac/s3-replicator.tf
workflows/main.tf

V6.0.0.0 rc

---

CHANGELOG.md
daac/s3-replicator.tf
workflows/main.tf

* Upgrades for Cumulus [v8.1.1.0](https://github.com/nasa/cumulus/releases/tag/v8.1.1)

Updates for Cumulus v8.1.1

---

CHANGELOG.md
Makefile
cumulus/variables/dev.tfvars
daac/s3-replicator.tf
data-migration1/variables/example.tfvars
rds/main.tf
rds/outputs.tf
rds/secrets/example.tfvars
rds/variables.tf
rds/variables/example.tfvars
rds/versions.tf
workflows/main.tf

adding information necessary for adding RDS.

cumulus 9.2.0 upgrade

---

CHANGELOG.md
daac/s3-replicator.tf
rds/main.tf
workflows/main.tf

Related: https://github.com/asfadmin/CIRRUS-core/pull/127

upgrade to Cumulus v10.1.2

---

CHANGELOG.md

See https://github.com/asfadmin/CIRRUS-core/pull/130

update changelog for CIRRUS-core's v11.1.0.1 changes

---

jenkins/Jenkinsfile

Set Jenkins script to use bash

---

.gitignore
.gitmodules
CHANGELOG.md
Makefile
README.md
cumulus/provider.tf
daac/dashboard.tf
daac/main.tf
daac/terraform.tfvars
daac/variables.tf
jenkins/Jenkinsfile

These commits are cherry picked from https://github.com/asfadmin/CIRRUS-ASF/pull/143

PR-3162 Cumulus Dashboard

---

CHANGELOG.md
daac/s3-replicator.tf
rds/main.tf
workflows/main.tf

NSIDC needs a bug fix from Cumulus 11.1.3 so creating a CIRRUS release for that version.

upgrade Cumulus to v11.1.3

---

CHANGELOG.md
daac/s3-replicator.tf
rds/main.tf
workflows/main.tf

V11.1.4.0 rc

---

CHANGELOG.md
daac/s3-replicator.tf
rds/main.tf
workflows/main.tf

updates for Cumulus v11.1.5

---

workflows/dev-requirements.txt

The following vulnerabilities are fixed by pinning transitive dependencies:
- https://snyk.io/vuln/SNYK-PYTHON-SETUPTOOLS-3180412

fix: workflows/dev-requirements.txt to reduce vulnerabilities

---

CHANGELOG.md
rds/main.tf
rds/variables.tf

We'll probably also need to merge these changes into master. I haven't really managed repos with multiple supported version branches before so I'm not really sure what the best approach is. Off the top of my head I'm thinking there are basically 2 choices:
1. Merge to v11 then merge v11 to master and resolve conflicts
2. Merge to v11 then cherry pick and make a new PR to master

PR-3829 Bump engine version to latest version of 11.x

---

CHANGELOG.md
Dockerfile
daac/s3-replicator.tf
rds/main.tf
workflows/main.tf

Cumulus v18.0.0 support

---

daac/dashboard.tf
daac/locals.tf

Turns out you can't uses tuples/lists in for_each statements. You need to use maps/sets. Also the dashboard bucket was missing the DAR tag.
This is a fix for changes added in #99

Fix daac deployment

---

daac/dashboard.tf
daac/locals.tf

Reverts asfadmin/CIRRUS-DAAC#101 This is still in a non working state. Related to work to be done yet in #102 its not been tested. In plans to release v18.3.1 this will be removed and come in a future release.

Revert "Fix daac deployment"

---

CHANGELOG.md
daac/distribution_bucket_policy.tf
daac/locals.tf
daac/terraform.tfvars
daac/variables.tf
daac/variables/sbx.tfvars

Reverts asfadmin/CIRRUS-DAAC#99 Part 2 of reverting from #109 work to be fixed in #102

Revert "Refactor bucket config to use a single map"

---

daac/dashboard.tf

adds dar dashboard tagging from #101

feat: add dar to dashboard bucket

---

CHANGELOG.md
daac/s3-replicator.tf
rds/main.tf
workflows/main.tf

I didn't see any changes that require modifications beyond bumping the version number. Seems like deployment to production will be the biggest lift for this release.

PR-6138 Update Cumulus to v18.4.0

---

CHANGELOG.md
daac/s3-replicator.tf
rds/main.tf
rds/variables.tf
rds/variables/example.tfvars
workflows/main.tf

PR-6140 Upgrade DAAC with cumulus v18.5.0

---

CHANGELOG.md
Makefile
cumulus/provider.tf
daac/provider.tf
dashboard/provider.tf
workflows/provider.tf

Pulling in some of the cleanup I've been making for supporting deploys from the host. See https://github.com/asfadmin/CIRRUS-core/pull/215

PR-6400 Cleanup
